### ISSUE TITLE
Bloated crate size

### ISSUE THREAD

**Issue by vi** [dermesser/leveldb-rs#2]
Seems like data for testing got into crates.io release, bloating it up to 5 MB.

It is shown as number one wasteful crate here: https://the-lean-crate.github.io/waste/rusty-leveldb/

[`tooldb`](https://docs.rs/crate/rusty-leveldb/0.3.3/source/tooldb/) may be extra.

**Comment by dermesser** [comment]
thank you for noticing, indeed it was some example data I forgot to remove before publishing!

**Comment by vi** [comment]
It is recommended to set [the `include` line](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) to avoid such things in future.

**Comment by dermesser** [comment]
thanks, I added it.
