### ISSUE TITLE
when multi-thread support? 

### ISSUE THREAD

**Issue by viraladmin** [dermesser/leveldb-rs#42]
When will multi-threaded DB be coming... the wait for lock release is such a huge flaw .... that really needs fixed asap especially for a code release claiming to be at version 3.... 

I spent days integrating completely over looking that tiny little note.... that seems to still be coming soon.... according to the docs. 

So I am stuck looking for other implementations but this seems to be the only real active and working implimenation of leveldb in rust.... 

Please oh please release this... soon....

**Comment by dermesser** [comment]
> When will multi-threaded DB be coming... the wait for lock release is such a huge flaw .... that really needs fixed asap especially for a code release claiming to be at version 3....
>

ever heard of semver? Moreover, never did I make a claim of being multi-thread-capable, or even just planning for it.

> I spent days integrating completely over looking that tiny little note.... that seems to still be coming soon.... according to the docs.

OK - you mean, like, one of the two sentences covering the central type in this library? Displayed right at the top?

> 
> So I am stuck looking for other implementations but this seems to be the only real active and working implimenation of leveldb in rust....
> 
> Please oh please release this... soon....

???
