### ISSUE TITLE
Possible memory leak when use iterator

### ISSUE THREAD

**Issue by SergeyPalam** [dermesser/leveldb-rs#51]
I write some code for testing crate: 
```
use memory_stats::memory_stats;
use rusty_leveldb::{DB, LdbIterator, Options};

fn mem_trace(msg: &str){
    if let Some(usage) = memory_stats() {
        println!("Current virtual memory usage in {}: {}", msg, usage.virtual_mem);
    }
}

fn iterate_over_db() {
    let mut opts = Options::default();
    opts.create_if_missing = false;
    let mut db = DB::open("leveldb", opts).unwrap();
    let mut iter = db.new_iter().unwrap();
    while let Some((_, _)) = iter.next() {
    }
}

fn main() {
    mem_trace("Before use LDB");
    iterate_over_db();
    mem_trace("After use LDB");
}
```
and find that after iterate_over_db() allocated memory hasn't freed. For "leveldb" I use local storage Google Chrome.

**Comment by dermesser** [comment]
It's possible that there are some cyclic references keeping some objects alive, that's unfortunate of course. Can you tell me some details on how much memory is being leaked?

**Comment by dermesser** [comment]
It was actually a much smaller issue than I had feared: the issue is that blocks carried around a copy of `Options`, which contained the block cache, which contained the options... having fixed that, valgrind reports no more leaks.

**Comment by dermesser** [comment]
Was this the case after v3.0.2, or did you notice this before the fix was released?
